# Generated by Django 5.0 on 2025-12-27 17:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='tiffin_app.tenant')),
            ],
            options={
                'ordering': ['-date', 'meal_type', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='tiffin_app.dailymenu'),
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(blank=True, max_length=200)),
                ('qty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tiffin_app.dailymenu')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiffin_app.dish')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailymenu',
            constraint=models.UniqueConstraint(fields=('tenant', 'date', 'meal_type'), name='uniq_daily_menu_tenant_date_mealtype'),
        ),
        migrations.AddConstraint(
            model_name='dailymenuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('dish__isnull', False)), fields=('daily_menu', 'dish'), name='uniq_menu_item_menu_dish'),
        ),
        migrations.AddConstraint(
            model_name='dailymenuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('dish__isnull', True), models.Q(('dish_name', ''), _negated=True)), fields=('daily_menu', 'dish_name'), name='uniq_menu_item_menu_dishname'),
        ),
    ]
