# Generated by Django 5.0 on 2025-12-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0002_dailymenu_dailyentry_menu_dailymenuitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'ordering': ['-date', 'meal_type', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='dailymenu',
            name='uniq_daily_menu_tenant_date_mealtype',
        ),
    ]
