# Generated by Django 5.0 on 2025-12-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0003_alter_dailymenu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='menu_name',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddConstraint(
            model_name='dailymenu',
            constraint=models.UniqueConstraint(condition=models.Q(('menu_name__isnull', False), models.Q(('menu_name', ''), _negated=True)), fields=('tenant', 'date', 'meal_type', 'menu_name'), name='uniq_menu_by_name'),
        ),
    ]
