# Generated by Django 5.0 on 2025-12-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0004_dailymenu_menu_name_dailymenu_uniq_menu_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='meal_type',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BOTH', 'Both')], max_length=10),
        ),
    ]
