# Generated by Django 5.0 on 2025-12-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0005_alter_dailymenu_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_customer',
            field=models.BooleanField(default=True),
        ),
    ]
