# Generated by Django 5.0 on 2026-01-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0006_customer_daily_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='meal_preference',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BOTH', 'Both')], max_length=10),
        ),
    ]
