# Generated by Django 5.0 on 2026-01-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0007_customer_meal_preference_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together=set(),
        ),
    ]
