# Generated by Django 5.0 on 2026-02-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0008_alter_dailyentry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='food_type',
            field=models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg'), ('BOTH', 'Both')], default='VEG', max_length=10),
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tiffin_app.customer')),
            ],
            options={
                'ordering': ['label', 'id'],
            },
        ),
    ]
