# Generated by Django 6.0 on 2026-02-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0009_customer_food_type_customerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
