# Generated by Django 5.0 on 2026-03-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0010_dailyentry_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='daily_lunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='is_default_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='is_default_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='meal_type',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
    ]
