# Generated by Django 6.0 on 2026-03-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin_app', '0011_customer_daily_dinner_customer_daily_lunch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dinner_portion',
            field=models.CharField(choices=[('HALF', 'Half'), ('FULL', 'Full')], default='FULL', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='lunch_portion',
            field=models.CharField(choices=[('HALF', 'Half'), ('FULL', 'Full')], default='FULL', max_length=10),
        ),
    ]
